version: "3.9"
services:
    automation:
        container_name: automation
        build:
          context: .
          dockerfile: dockerfile
        ports:
            - "2112:2112"
            # - "5296:5296"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default


networks:
  default:
    driver:  bridge

  